version: "2"
run:
  tests: true
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funcorder
    - gochecknoglobals
    - ireturn
    - lll
    - mnd
    - nolintlint
    - nonamedreturns
    - paralleltest
    - tagliatelle
    - testifylint
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    depguard:
      rules:
        Main:
          files:
            - '!**.go'
          allow:
            - $gostd
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocyclo:
      min-complexity: 20
    misspell:
      locale: US
    unparam:
      check-exported: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - containedctx
          - dupl
          - err113
          - exhaustruct
          - funlen
          - goconst
          - mnd
          - noctx
        path: _test.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 20
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
