# See https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  tests: true

linters-settings:
  depguard:
    rules:
      Main:
        files:
          - "!**.go"
        allow:
          - $gostd
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  misspell:
    locale: US
  unparam:
    check-exported: true

linters:
  enable-all: true
  disable:
    - depguard
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - gci
    - gochecknoglobals
    - ireturn
    - lll
    - mnd
    - nonamedreturns
    - nolintlint # https://github.com/golangci/golangci-lint/issues/3063
    - paralleltest
    - tagliatelle
    - tenv
    - testifylint
    - testpackage
    - varnamelen
    - wrapcheck

issues:
  max-same-issues: 20
  exclude-use-default: false
  exclude-rules:
    - linters:
        - containedctx
        - dupl
        - err113
        - exhaustruct
        - funlen
        - goconst
        - mnd
        - noctx
      path: "_test.go"
